#!/usr/bin/env node

const fs = require("fs")
const path = require("path")

console.log("🚀 Setting up GraphQL integration...")

// Create .env.local if it doesn't exist
const envPath = path.join(process.cwd(), ".env.local")
const envExample = `# API Configuration
NEXT_PUBLIC_API_BASE_URL=http://localhost:4200/
NEXT_PUBLIC_GRAPHQL_ENDPOINT=http://localhost:4200/graphql

# Feature Flags
NEXT_PUBLIC_USE_GRAPHQL=false

# Analytics
NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID=GTM-N6WPVHXW
NEXT_PUBLIC_MICROSOFT_CLARITY_ID=qamligptbk`

if (!fs.existsSync(envPath)) {
	fs.writeFileSync(envPath, envExample)
	console.log("✅ Created .env.local file with default configuration")
} else {
	console.log(
		"ℹ️  .env.local already exists - please add GraphQL configuration manually"
	)
}

// Create generated directory
const generatedDir = path.join(process.cwd(), "src", "generated")
if (!fs.existsSync(generatedDir)) {
	fs.mkdirSync(generatedDir, { recursive: true })
	console.log("✅ Created src/generated directory")
}

// Create a placeholder for generated files
const placeholderContent = `// This file will be generated by GraphQL Code Generator
// Run 'npm run codegen' to generate types and hooks

export const placeholder = 'Run npm run codegen to generate GraphQL types'`

const generatedFile = path.join(generatedDir, "graphql.ts")
if (!fs.existsSync(generatedFile)) {
	fs.writeFileSync(generatedFile, placeholderContent)
	console.log("✅ Created placeholder for generated GraphQL types")
}

console.log(`
🎉 GraphQL setup complete!

Next steps:
1. Update your .env.local with the correct GraphQL endpoint
2. Start your GraphQL backend server
3. Run 'npm run codegen' to generate types
4. Set NEXT_PUBLIC_USE_GRAPHQL=true to enable GraphQL
5. Visit /test-graphql to test the integration

For more details, see GRAPHQL_SETUP.md
`)
